### 목표
- 특성변수 활용하여 회귀 예측을 진행해보자
- 데이터를 활용하기 위해 특성곱이라고 하는 특성공학을 진행해보자

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# 보스턴 주택가격 데이터
from sklearn.datasets import load_boston

import warnings
warnings.filterwarnings(action='ignore')


In [5]:
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [7]:
# key 값만 확인하기 
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [12]:
# 문제 데이터
boston.data

# 문제 특성 이름
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

### 부동산 데이터
CRIM: 범죄율  
ZN: 25,000 평방피트를 초과 거주지역 비율  
INDUS: 일산화질소 농도  
CHAS: 찰스강의 경계에 위치한 경우는 1, 아니면 0  
NOX: 일산화질소 농도   
RM: 주택당 방 수  
AGE: 1940년 이전에 건축된 주택의 비율  
DIS : 직업센터의 거리   
TAX : 재산세율 
PTRATIO : 학생/교사 비율  
B : 인구 중 흑인 비율  
LSTAT : 인구중 하위 계층 비율  

In [14]:
# 답 데이터 - 수치형 데이터 : 주택가격
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

### 데이터 전처리
- 분석편리 : 넘파이 배열 -> df
- X: 문제, 독립변수, 특성, 피처, 설명변수, 입력변수  
- y: 답, 종속변수, 타겟, 반응변수, 출력변수

In [15]:
# df, 컬럼명 : 피처이름들 연결
X = pd.DataFrame(boston.data, 
                 columns=boston.feature_names)
y = pd.Series(boston.target)

In [16]:
# 위에서 다섯개 행 출력 
# head()
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [17]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
dtype: float64

- train, test 분리 
    - train 학습용, test 테스트용(성능평가) 
    - train_test_split 함수를 이용하여 train, test 생성
    - 7:3, random_state = 0
    - X_train, X_test, y_train, y_test

In [20]:
from sklearn.model_selection import train_test_split
# 1. 행 무작위로 섞임 2. 비율대로 분리 => 랜덤 샘플링 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,
                                                    random_state = 0)

In [22]:
# 크기 확인
print('훈련문제 : ', X_train.shape)
print('훈련답: ', y_train.shape)
print('테스트문제 : ', X_test.shape)
print('테스트답 : ', y_test.shape)

훈련문제 :  (354, 13)
훈련답:  (354,)
테스트문제 :  (152, 13)
테스트답 :  (152,)


In [25]:
# 다른 전처리 필요 x
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 152 entries, 329 to 5
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     152 non-null    float64
 1   ZN       152 non-null    float64
 2   INDUS    152 non-null    float64
 3   CHAS     152 non-null    float64
 4   NOX      152 non-null    float64
 5   RM       152 non-null    float64
 6   AGE      152 non-null    float64
 7   DIS      152 non-null    float64
 8   RAD      152 non-null    float64
 9   TAX      152 non-null    float64
 10  PTRATIO  152 non-null    float64
 11  B        152 non-null    float64
 12  LSTAT    152 non-null    float64
dtypes: float64(13)
memory usage: 16.6 KB


### LinearRegression

In [26]:
# 모델
from sklearn.linear_model import LinearRegression
# 교차검증
from sklearn.model_selection import cross_val_score

In [29]:
# 모델 생성
linear_model = LinearRegression()

# 모델 학습
linear_model.fit(X_train, y_train)

# 모델 예측
pre = linear_model.predict(X_test)

In [30]:
pre

array([24.9357079 , 23.75163164, 29.32638296, 11.97534566, 21.37272478,
       19.19148525, 20.5717479 , 21.21154015, 19.04572003, 20.35463238,
        5.44119126, 16.93688709, 17.15482272,  5.3928209 , 40.20270696,
       32.31327348, 22.46213268, 36.50124666, 31.03737014, 23.17124551,
       24.74815321, 24.49939403, 20.6595791 , 30.4547583 , 22.32487164,
       10.18932894, 17.44286422, 18.26103077, 35.63299326, 20.81960303,
       18.27218007, 17.72047628, 19.33772473, 23.62254823, 28.97766856,
       19.45036239, 11.13170639, 24.81843595, 18.05294835, 15.59712226,
       26.21043403, 20.81140432, 22.17349382, 15.48367365, 22.62261604,
       24.88561528, 19.74754478, 23.0465628 ,  9.84579105, 24.36378793,
       21.47849008, 17.62118176, 24.39160873, 29.95102691, 13.57219422,
       21.53645439, 20.53306273, 15.03433182, 14.3232289 , 22.11929299,
       17.07321915, 21.54141094, 32.96766968, 31.371599  , 17.7860591 ,
       32.75069556, 18.74795323, 19.21428022, 19.41970047, 23.08

In [32]:
# 교차 검증 : 일반적인 성능 확인
# 교차검증 5번, train 사용
result = cross_val_score(linear_model, X_train, y_train, cv = 5)

result

array([0.7246982 , 0.58082515, 0.77515092, 0.72161474, 0.78935797])

In [33]:
result.mean()

0.718329397431593

#### 선형회귀 평가 지표 
- 여러 머신러닝 모델들을 사용했을 때 성능 지표를 보고 모델을 비교하기 때문에 정량적인 지표가 중요
    - mse : 평균제곱오차
    - rmse : 평균제곱오차에 루트를 씌운 것
    - mae : 오차를 절댓값으로 변환해 평균한 것
    - r2 : R-Squared, 분산 기반 예측 성능 평가, 실제값의 분산과 예측값의 분산을 비교, 모델.score(), 0~1, 1에 가까울수록 모델의 성능이 좋다.

### 사이킷런 LinearRegression을 이용한 보스턴 주택 가격 예측

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_boston
import warnings
warnings.filterwarnings('ignore')

# boston 데이터셋 로드
boston = load_boston()

# boston 데이터셋 DataFrame 변환 
bostonDF = pd.DataFrame(boston.data, columns = boston.feature_names)

# boston dataset의 target array는 주택가격. price 칼럼으로 DataFrame에 추가
bostonDF['PRICE'] = boston.target
print('Boston 데이터셋 크기 : ', bostonDF.shape)
bostonDF.head()

Boston 데이터셋 크기 :  (506, 14)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

- CRIM : 지역별 범죄 발생률 
- ZN : 25,000평방피트를 초과하는 거주 지역의 비율
- INDUS: 비상업 지역 넓이 비율
- CHAS: 찰스강의 경계에 위치한 경우는 1, 아니면 0  
- NOX: 일산화질소 농도   
- RM: 거주할 수 있는 방 개수
- AGE: 1940년 이전에 건축된 주택의 비율  
- DIS : 5개 주요 고용센터까지의 거리   
- TAX : 10,000달러당 재산세율 
- PTRATIO : 지역의 학생/교사 비율  
- B : 인구 중 흑인 비율  
- LSTAT : 인구중 하위 계층 비율  
- MEDV : 본인 소유의 주택 가격(중앙값)